### ISSUE TITLE
[Bug]: It's not working..

### ISSUE THREAD

**Issue by Reno0vacio** [phibr0/obsidian-tabout#15]
### Describe the bug

Simply doesn't work. I installed and enabled it, but it doesn't work in either the "environment" or anywhere else. It simply creates a "quoted block".

Tabout 1.0.0 version
Obsidian 1.4.14

### Steps to reproduce

Install the plugin..

### Operating system

Windows

**Comment by Lisandra-dev** [comment]
I have the same issue

**Comment by vishae** [comment]
When I first installed the plugin, I also noticed that none of the pre-existing rules worked.

But try the following steps:

1. Type **placeholder** into your document
2. Put the cursor somewhere within the word "placeholder"
3. Run the command “Add Rule for this Environment”.
4. Type "**" in the "Characters" field.
5. Click "Add this Rule"

You will find that tabout now works with the ** ** environment.
Repeat that with all the other environments you want to tabout of (eg. [], [[]], **strong**, _em_)

**Note:** Always type some words between the open and closing characters otherwise tabout might use the wrong environment.

**Comment by Reno0vacio** [comment]
@vishae  Thank you, but i tried, and yes.. it works with the ** but that's it.. It doesn't work with any of the other: "", [], [[]], `, symbols..

**Comment by vishae** [comment]
@Reno0vacio For the "", did you add the other symbols to your rule?

Example.
<img width="572" alt="image" src="https://github.com/phibr0/obsidian-tabout/assets/6110232/d70869dc-7b17-4242-aa2b-87e3a0e73e82">

For the [] and [[]], you need rules that points to "formatting_formatting-link_hmd-barelink_link" and "formatting-link_formatting-link-start" environments respectively.

<img width="794" alt="image" src="https://github.com/phibr0/obsidian-tabout/assets/6110232/6606e8ae-00fd-4bf0-a48d-53016b401311">

<img width="1099" alt="image" src="https://github.com/phibr0/obsidian-tabout/assets/6110232/c1dac7c2-1c75-41db-aad5-fea9a82ecb13">

But it's easier to create those rules using the steps I mentioned above (ie. type [placeholder] in your editor, have the cursor in the world "placeholder" and run the command, “Add Rule for this Environment”)

Let me know how you go.

**Comment by Lisandra-dev** [comment]
Will lvoe a sharing file!

**Comment by vishae** [comment]
@TamingTheMammoth sure
[data.json](https://github.com/phibr0/obsidian-tabout/files/13625321/data.json)

**Comment by notuntoward** [comment]
I have the same problem as @Reno0vacio.  After I tried @vishae's `data.json`, it was still the same.  Tabout worked only for `** **`, and made a quoted block for anything else.

**Comment by Sprocketer** [comment]
> I have the same problem as @Reno0vacio. After I tried @vishae's `data.json`, it was still the same. Tabout worked only for `** **`, and made a quoted block for anything else.

same @vishae - what do your obsidian hotkeys look like?

**Comment by vishae** [comment]
hey @notuntoward and @Sprocketer, instead of using my data.json file, I suggest you follow the instructions I provided on the 17th Nov and 22nd Nov to build your own rules/data.json.

Environments change when Obsidian updates their code or depending on the theme you're using. As such, my data.json file may not work for you.

As a refresher:
1. Go to the document in Obsidian with the ** ** or " " or whatever you want to tab out of
2. Place your cursor within the ** ** or " " or whatever
3. Activate Command Palette (default hotkey is Cmd/Win+P)
4. Find the Tabout command, "Add Rule for this Environment" and click on it
5. In the "Characters" field, type in ** or " or ) or whatever closing character you want
7. Click "Add this Rule" when you're done

You would need to create one of these for every set of characters (eg. " ", ' ', ( ), [ ], [[ ]]) you want to tab out of.
You also need to create a set of those rules for every "environment" you want the rules to activate (explanation of what "environment" is below).

Instead of creating them all in one go, I suggest only creating them as you need.

If you open the Tabout settings, you will see the existing rules you have:
![image](https://github.com/phibr0/obsidian-tabout/assets/6110232/e3b60aab-ee7b-4bd2-b80a-9306a47d6699)

Clicking "Edit" will show you details about the rules:
![image](https://github.com/phibr0/obsidian-tabout/assets/6110232/6da1e472-42af-4313-be82-215ff06f2aee)

If you followed the above instructions in just a plain document, most likely your first "environment" is "document".
What this means is if you want to tab out of a header in your document, for example: `## This is a header (and I want to tabout of the brackets)` then you'll need to put your cursor within the header and follow the instructions above. You'll need a separate set of rules for H1, H2, H3 etc.

It may seem like a lot of work, but you'll find you only need to use these for a handful of environments, and you only need to redo this if there's been a major change in Obsidian.

**Note 1:** This doesn't work for list environments. If you tab in a list, the list would just indent instead of tabbing out. I mean, I would love it if it tabbed out of the () or whatever first and then indent, but the plugin doesn't seem that smart.

**Note 2:** For the internal links [] [[]], in my post on the 22nd Nov, I mentioned the environments "formatting_formatting-link_hmd-barelink_link" and "formatting-link_formatting-link-start" respectively. Do not use these, as they have changed in Obsidian.
Just follow my instructions above to create them, the plugin will automatically discover the environment you need.

**Comment by Sprocketer** [comment]
@vishae Got it done last night - a bit annoying that you can't set rules for all headers / all indents of unordered lists but it works I guess

**Comment by notuntoward** [comment]
Thanks, @vishae, for the meticulous tips.
